"use strict";

// Des scénarios plausibles pour un jeu fictif. Aucun détail graphique.
// Les groupes servent seulement à organiser les possibilités ; le tirage est uniforme.
const DEATH_GROUPS = [
  [
    "de vieillesse, paisiblement chez toi", "de vieillesse, entouré de ta famille", "de vieillesse dans ton sommeil", "de vieillesse après une longue retraite", "de vieillesse après avoir rencontré tes arrière-petits-enfants", "de vieillesse à l'hôpital", "de vieillesse dans une maison de retraite", "de vieillesse pendant des vacances en famille", "de vieillesse après une vie de voyages", "de vieillesse dans ta ville natale", "de vieillesse dans la maison où tu as grandi", "de vieillesse après un dernier repas de famille", "de vieillesse au bord de la mer", "de vieillesse à la campagne", "de vieillesse après avoir passé l'après-midi au jardin", "de vieillesse un matin d'hiver", "de vieillesse un soir d'été", "de vieillesse après une vie consacrée à tes proches", "de vieillesse après avoir fêté tes 100 ans", "de vieillesse, aux côtés de la personne que tu aimes"
  ],
  [
    "à la suite d'un accident de voiture sur l'autoroute", "à la suite d'un accident de voiture sur une route de campagne", "à la suite d'un accident de voiture en rentrant du travail", "à la suite d'un accident de voiture pendant les vacances", "à la suite d'un accident de voiture de nuit", "à la suite d'un accident de voiture sous une forte pluie", "à la suite d'un accident de voiture sur une route verglacée", "à la suite d'un accident de voiture à un carrefour", "à la suite d'un accident de voiture en montagne", "à la suite d'un accident de voiture lors d'un long trajet", "à la suite d'un accident de moto sur l'autoroute", "à la suite d'un accident de moto en ville", "à la suite d'un accident de moto sur une route sinueuse", "à la suite d'un accident de scooter à un carrefour", "à la suite d'un accident de scooter en rentrant chez toi", "à la suite d'un accident de vélo en ville", "à la suite d'un accident de vélo sur une route départementale", "à la suite d'un accident de vélo lors d'une sortie sportive", "à la suite d'un accident de camion sur la route", "à la suite d'un accident de bus pendant un voyage", "après avoir été renversé en traversant la rue", "après avoir été renversé sur un passage piéton", "après avoir été renversé par un véhicule de nuit", "dans une collision entre deux voitures à une intersection", "dans un accident de la route pendant un trajet en taxi", "dans un accident de la route alors que tu étais passager", "dans un accident de la route pendant un déménagement", "dans un accident de la route sur le chemin de l'aéroport", "dans un accident de voiture provoqué par le brouillard", "dans un accident de voiture lors d'une tempête"
  ],
  [
    "à la suite d'un accident vasculaire cérébral", "à la suite d'un infarctus", "à la suite d'un arrêt cardiaque pendant ton sommeil", "à la suite d'un arrêt cardiaque lors d'une promenade", "à la suite d'une maladie cardiaque", "à la suite d'une insuffisance respiratoire", "à la suite d'une infection pulmonaire", "à la suite d'une pneumonie", "à la suite d'une infection grave", "à la suite d'une septicémie", "à la suite d'une insuffisance rénale", "à la suite d'une insuffisance hépatique", "à la suite d'une maladie neurologique", "à la suite d'une maladie dégénérative", "à la suite d'une longue maladie", "à la suite d'une maladie rare", "à la suite d'un cancer du poumon", "à la suite d'un cancer du sein", "à la suite d'un cancer colorectal", "à la suite d'un cancer du pancréas", "à la suite d'une leucémie", "à la suite d'une tumeur cérébrale", "à la suite d'une complication postopératoire", "à la suite d'une complication lors d'une intervention médicale", "à la suite d'une réaction allergique grave", "à la suite d'une embolie pulmonaire", "à la suite d'une rupture d'anévrisme", "à la suite d'une maladie auto-immune", "à la suite d'une grippe compliquée", "à la suite d'une complication liée au diabète", "à la suite d'une maladie infectieuse contractée en voyage", "à la suite d'une maladie tropicale", "à la suite d'une défaillance de plusieurs organes", "à la suite d'une crise d'asthme sévère", "à la suite d'une hémorragie interne"
  ],
  [
    "dans un incendie domestique", "dans un incendie d'immeuble", "dans un incendie à l'hôtel", "dans un incendie de forêt près de chez toi", "dans un incendie sur ton lieu de travail", "à la suite d'une fuite de gaz chez toi", "à la suite d'une intoxication au monoxyde de carbone", "à la suite d'une intoxication accidentelle", "à la suite d'une chute dans l'escalier", "à la suite d'une chute depuis un balcon", "à la suite d'une chute en réparant le toit", "à la suite d'une chute en bricolant chez toi", "à la suite d'une chute dans ta salle de bain", "à la suite d'une chute d'une échelle", "à la suite d'un accident lors de travaux dans ton jardin", "à la suite d'un accident avec un outil de bricolage", "à la suite d'un accident dans une piscine privée", "à la suite d'une électrocution en réparant un appareil", "à la suite de l'effondrement d'un bâtiment", "à la suite de la chute d'un arbre pendant une tempête", "après t'être étouffé pendant un repas", "à la suite d'un accident en déplaçant un meuble lourd", "à la suite d'une inondation dans ton quartier", "à la suite d'un accident dans une cave inondée", "à la suite d'une chute sur un sol verglacé"
  ],
  [
    "dans une avalanche en montagne", "dans une avalanche pendant une sortie à ski", "dans une avalanche lors d'une randonnée hivernale", "à la suite d'une chute en randonnée", "à la suite d'une chute en escalade", "à la suite d'une chute sur un sentier de montagne", "après t'être perdu en montagne par mauvais temps", "à la suite d'une tempête en mer", "à la suite d'un naufrage", "à la suite d'un accident de bateau", "à la suite d'un accident de kayak", "à la suite d'une noyade dans un lac", "à la suite d'une noyade en mer", "à la suite d'une noyade dans une rivière", "à la suite d'un accident de plongée", "à la suite d'un accident de surf", "à la suite d'une crue soudaine", "à la suite d'une vague de chaleur", "à la suite d'une hypothermie pendant une randonnée", "à la suite d'un orage violent", "après avoir été frappé par la foudre", "à la suite d'un glissement de terrain", "à la suite d'un tremblement de terre", "à la suite d'un tsunami pendant un voyage", "à la suite d'une tempête de neige", "à la suite d'une chute de pierres en montagne", "à la suite d'une collision avec un animal sauvage sur la route", "à la suite d'une piqûre provoquant une réaction allergique sévère", "à la suite d'une attaque d'animal sauvage", "à la suite d'une déshydratation en pleine chaleur"
  ],
  [
    "à la suite d'un accident de ski", "à la suite d'un accident de snowboard", "à la suite d'un accident de parapente", "à la suite d'un accident de parachutisme", "à la suite d'un accident d'équitation", "à la suite d'un accident de karting", "à la suite d'un accident sur circuit automobile", "à la suite d'un accident pendant une course cycliste", "à la suite d'un accident de VTT", "à la suite d'un accident en escalade", "à la suite d'un accident de spéléologie", "à la suite d'un accident de rafting", "à la suite d'un accident de voile", "à la suite d'un accident de jet-ski", "à la suite d'un accident de randonnée", "à la suite d'un accident de chasse", "à la suite d'un accident lors d'un saut à l'élastique", "à la suite d'un malaise pendant un marathon", "à la suite d'un malaise pendant une séance de sport", "à la suite d'un accident de trottinette électrique", "à la suite d'un accident de skateboard", "à la suite d'une chute pendant une course à pied", "à la suite d'un accident de luge", "à la suite d'un accident en pratiquant l'alpinisme", "à la suite d'un accident pendant une sortie en canoë"
  ],
  [
    "à la suite d'un accident sur un chantier", "à la suite d'une chute sur ton lieu de travail", "à la suite d'un accident dans une usine", "à la suite d'un accident dans un entrepôt", "à la suite d'un accident lors d'une livraison", "à la suite d'un accident pendant un déplacement professionnel", "à la suite d'un accident avec une machine industrielle", "à la suite d'une chute d'échafaudage", "à la suite d'un accident agricole", "à la suite d'un accident en mer pendant une mission professionnelle", "à la suite d'un incendie dans un atelier", "à la suite d'une intoxication sur un site industriel", "à la suite d'un accident pendant des travaux électriques", "à la suite d'un accident dans une mine", "à la suite d'un accident sur une plateforme pétrolière", "à la suite d'un accident sur une ligne ferroviaire", "à la suite d'un accident lors d'une intervention de secours", "à la suite d'un accident en conduisant pour ton travail", "à la suite d'un accident dans une cuisine professionnelle", "à la suite d'un accident pendant la rénovation d'un bâtiment", "à la suite de la chute d'une charge dans un entrepôt", "à la suite d'un accident dans un port", "à la suite d'un accident pendant un tournage", "à la suite d'un accident de grue sur un chantier", "à la suite d'une explosion accidentelle dans une usine"
  ],
  [
    "dans un accident d'avion", "dans un accident d'hélicoptère", "dans un accident de petit avion de tourisme", "dans un accident de train", "dans un accident de métro", "dans un accident de tramway", "dans un accident de ferry", "dans un accident de bateau de pêche", "à la suite d'un accident lors d'une croisière", "à la suite d'un accident pendant un voyage en montagne", "à la suite d'un accident lors d'un safari", "à la suite d'un accident pendant un séjour à l'étranger", "à la suite d'un accident sur une route inconnue pendant les vacances", "à la suite d'une noyade pendant les vacances", "à la suite d'un accident de scooter en voyage", "à la suite d'une chute pendant une visite touristique", "à la suite d'un accident dans un parc d'attractions", "à la suite d'un accident de montgolfière", "à la suite d'un accident de télécabine", "à la suite d'un accident de bus touristique", "à la suite d'un accident de randonnée pendant les vacances", "à la suite d'un accident en traversant une rivière en voyage", "à la suite d'une tempête pendant une croisière", "à la suite d'un accident de plongée pendant les vacances", "à la suite d'un accident de la route au retour des vacances"
  ],
  [
    "à la suite d'un malaise dans les transports", "à la suite d'un malaise au travail", "à la suite d'un malaise pendant un voyage", "à la suite d'un malaise à domicile", "à la suite d'un malaise dans la rue", "à la suite d'un arrêt cardiaque au travail", "à la suite d'un arrêt cardiaque dans un train", "à la suite d'un arrêt cardiaque pendant un repas", "à la suite d'un arrêt cardiaque en vacances", "à la suite d'un accident vasculaire cérébral chez toi", "à la suite d'un accident vasculaire cérébral pendant un voyage", "à la suite d'une complication après une opération", "à la suite d'une infection contractée à l'hôpital", "à la suite d'une réaction allergique à un aliment", "à la suite d'une réaction allergique à un médicament", "à la suite d'une crise cardiaque lors d'une réunion de famille", "à la suite d'une crise cardiaque en faisant du jardinage", "à la suite d'une infection après une blessure", "à la suite d'une maladie découverte trop tard", "à la suite d'une complication d'une maladie chronique", "à la suite d'une insuffisance cardiaque", "à la suite d'une détresse respiratoire", "à la suite d'une méningite", "à la suite d'une infection virale grave", "à la suite d'une complication imprévue d'un traitement"
  ],
  [
    "à la suite d'une chute sur un quai de gare", "à la suite d'un accident sur un passage à niveau", "à la suite d'un accident sur un chantier routier", "à la suite d'une collision entre un vélo et une voiture", "à la suite d'une collision entre une moto et un camion", "à la suite d'une collision entre deux bus", "à la suite d'une collision entre un train et un véhicule", "à la suite d'un accident de voiture sous la neige", "à la suite d'un accident de voiture dans un tunnel", "à la suite d'un accident de voiture sur un pont", "à la suite d'un accident de voiture à la sortie d'un virage", "à la suite d'un accident de voiture sur le périphérique", "à la suite d'un accident de voiture après une longue journée", "à la suite d'un accident de voiture au lever du jour", "à la suite d'un accident de voiture pendant un trajet familial", "à la suite d'un accident de deux-roues sur une route mouillée", "à la suite d'un accident de vélo près de chez toi", "à la suite d'un accident de vélo sur le trajet du travail", "à la suite d'un accident de trottinette sur la route", "à la suite d'un accident de la route en traversant un village", "à la suite d'un accident de la route à un rond-point", "à la suite d'un accident de la route pendant une livraison", "à la suite d'un accident de la route sur le chemin de l'école", "à la suite d'un accident de la route en rentrant de vacances", "à la suite d'un accident de la route lors d'un voyage de nuit"
  ],
  [
    "à la suite d'un incendie dans un camping", "à la suite d'un incendie dans une résidence", "à la suite d'un incendie dans un restaurant", "à la suite d'un incendie dans un garage", "à la suite d'une explosion accidentelle dans un immeuble", "à la suite d'une explosion accidentelle sur un chantier", "à la suite d'une fuite de gaz dans un immeuble", "à la suite d'une intoxication au monoxyde de carbone dans un logement", "à la suite d'une intoxication au monoxyde de carbone pendant la nuit", "à la suite de la chute d'un arbre en promenade", "à la suite de la chute d'un objet lourd sur un chantier", "à la suite de la chute d'un élément de façade", "à la suite de l'effondrement d'un toit", "à la suite de l'effondrement d'un balcon", "à la suite d'un accident dans un ascenseur", "à la suite d'un accident lors d'une rénovation", "à la suite d'un accident sur une échelle au jardin", "à la suite d'un accident de bricolage dans un garage", "à la suite d'un accident dans une piscine municipale", "à la suite d'un accident dans une piscine d'hôtel", "à la suite d'un accident sur un sentier côtier", "à la suite d'une chute en descendant un escalier extérieur", "à la suite d'une chute dans une gare", "à la suite d'une chute lors d'une promenade nocturne", "à la suite d'une chute près d'une falaise"
  ],
  [
    "à la suite d'une inondation pendant une tempête", "à la suite d'une crue en traversant une route", "à la suite d'une crue pendant une randonnée", "à la suite d'une tempête sur un voilier", "à la suite d'une tempête en montagne", "à la suite d'une tempête tropicale pendant un voyage", "à la suite d'une vague de chaleur en ville", "à la suite d'une vague de chaleur pendant une randonnée", "à la suite d'une hypothermie en mer", "à la suite d'une hypothermie en montagne", "à la suite d'un orage pendant une randonnée", "à la suite d'un orage en pleine mer", "à la suite d'un glissement de terrain après de fortes pluies", "à la suite d'un glissement de terrain en montagne", "à la suite d'un séisme lors d'un voyage", "à la suite d'un séisme chez toi", "à la suite d'un feu de forêt près d'un camping", "à la suite d'un feu de forêt pendant une randonnée", "à la suite d'un accident de bateau sur un lac", "à la suite d'un accident de bateau en rivière", "à la suite d'une noyade au cours d'une baignade", "à la suite d'une noyade après un accident de bateau", "à la suite d'un accident dans une grotte", "à la suite d'une chute lors d'une promenade en forêt", "à la suite d'une avalanche près d'une station de ski"
  ],
  [
    "après une longue vie et une dernière promenade", "après une longue vie passée à enseigner", "après une longue vie passée à soigner les autres", "après une longue vie consacrée à ta famille", "après une longue vie passée à voyager", "après une longue vie dans le même village", "après une longue vie au bord de la mer", "après une longue vie remplie de projets", "après une longue vie entouré de tes amis", "après une longue vie passée à faire de la musique", "après une longue vie à tenir ton commerce", "après une longue vie à faire du sport", "après une longue vie passée à écrire", "après une longue vie à cultiver ton jardin", "après une longue vie à découvrir le monde", "après une longue vie paisible à la campagne", "après une longue vie dans la ville que tu aimais", "après une longue vie auprès de tes proches", "après une longue vie de découvertes", "après une longue vie remplie de souvenirs"
  ]
];
const DEATHS = Object.freeze(DEATH_GROUPS.flat());
