"use strict";

// Toutes les fins sont fictives, sans détail graphique.
// 273 fins ridicules + 91 fins plausibles : exactement 75 % de fins ridicules.
const RIDICULOUS_DEATHS = [
  "noyé en buvant une canette de Coca",
  "emporté par une vague de soupe au potiron",
  "pris au piège sous une montagne de popcorn",
  "vaincu par une baguette de pain trop croustillante",
  "perdu dans une fondue au fromage sans fond",
  "englouti par le dernier ravioli d'un buffet à volonté",
  "assommé par une pastèque en voulant choisir la plus mûre",
  "englouti par une avalanche de céréales au petit déjeuner",
  "submergé par une mousse de cappuccino géante",
  "coincé dans un distributeur en voulant récupérer un paquet de chips",
  "écrasé par le trophée du concours de mangeurs de frites",
  "emporté par une crêpe géante un jour de grand vent",
  "piégé dans un donut gonflable que personne ne pouvait arrêter",
  "vaincu par un cornichon lors d'un duel de regard",
  "perdu en cherchant la sortie d'une montagne de spaghettis",
  "enseveli sous 400 kilos de guimauves",
  "noyé dans un verre d'eau beaucoup trop ambitieux",
  "emporté par une vague de sirop de grenadine",
  "avalé par une machine à barbe à papa déréglée",
  "assommé par un ananas tombé d'un chapeau",
  "coincé dans un frigo rempli uniquement de yaourts",
  "renversé par une pyramide de boîtes de conserve",
  "vaincu par la sauce piquante « juste une goutte »",
  "disparu au fond d'un paquet de chips familial",
  "emporté par le coulis de chocolat d'une fontaine géante",
  "écrasé par un gâteau d'anniversaire à cent étages",
  "perdu dans un labyrinthe de rayons de supermarché",
  "pris au piège par un pigeon qui réclamait ta baguette",
  "renversé par un troupeau de canards en file indienne",
  "écrasé sous le poids d'un câlin de panda trop enthousiaste",
  "chassé du jardin par une armée d'escargots",
  "vaincu au bras de fer par une oie furieuse",
  "emporté par un lama qui refusait de rendre ton sandwich",
  "assommé par une tortue tombée d'un petit tabouret",
  "pris dans une embuscade de hamsters sur une roue géante",
  "renversé par un mouton qui voulait te dépasser",
  "poursuivi jusqu'au bout du monde par un caniche minuscule",
  "perdu dans un duel contre un paon trop fier",
  "renversé par un kangourou venu te voler ton sac",
  "coincé dans le terrier d'un lapin que tu voulais saluer",
  "vaincu par un poisson rouge au concours d'apnée",
  "emporté par un essaim de papillons très organisés",
  "assommé par un hibou qui avait raté son atterrissage",
  "piégé dans une réunion de famille de hérissons",
  "renversé par un cheval à bascule devenu incontrôlable",
  "écrasé par une peluche d'ours de taille réelle",
  "poursuivi par un cygne pour une miette de pain",
  "vaincu par une grenouille au concours de saut en hauteur",
  "perdu dans un élevage de lamas qui te prenaient pour leur chef",
  "renversé par une vache venue chercher sa photo",
  "assommé par une baleine gonflable échappée d'une piscine",
  "coincé entre deux pingouins qui se disputaient ton écharpe",
  "emporté par un chien qui croyait que tu étais sa balle",
  "écrasé par un coussin tombé de cinq centimètres",
  "perdu dans une housse de couette à la mauvaise taille",
  "pris au piège dans un canapé convertible trop rapide",
  "renversé par un aspirateur robot en colère",
  "assommé par une lampe de chevet en mousse",
  "coincé dans la porte d'un placard plein de chaussettes",
  "avalé par un panier à linge sans fond",
  "emporté par une pile de coussins décoratifs",
  "vaincu par le tiroir qui ne voulait jamais se fermer",
  "pris au piège sous une couverture lestée de plumes",
  "perdu dans ta propre armoire après avoir changé de place les étagères",
  "renversé par une chaise de bureau qui tournait trop vite",
  "coincé entre deux matelas lors d'un déménagement",
  "assommé par un rouleau de papier toilette géant",
  "englouti par une piscine de balles dans le salon",
  "vaincu par le piège de la porte qui s'ouvre vers toi",
  "emporté par un tapis roulant posé au milieu du couloir",
  "perdu en cherchant la télécommande dans le canapé",
  "coincé dans un tunnel de cartons de déménagement",
  "renversé par une plante verte qui voulait plus de lumière",
  "vaincu par une pile de livres jamais lus",
  "emporté par les rideaux pendant un courant d'air",
  "assommé par le balai en voulant le faire tenir debout",
  "coincé sous une montagne de manteaux sur une chaise",
  "perdu dans le tiroir des câbles qui ne servent à rien",
  "vaincu par une machine à laver qui réclamait ses chaussettes",
  "pris au piège par un réveil qui sonnait la veille",
  "aspiré par une mise à jour Windows interminable",
  "englouti par les 900 onglets ouverts sur ton navigateur",
  "vaincu par un CAPTCHA te demandant de reconnaître les vélos",
  "coincé dans la boucle infinie d'un mot de passe oublié",
  "assommé par la notification d'un message « salut »",
  "perdu dans un dossier nommé « nouveau dossier final 7 »",
  "emporté par un câble USB branché du mauvais côté trois fois",
  "piégé dans une visioconférence où personne ne trouvait le bouton quitter",
  "vaincu par un autocorrecteur qui écrivait à ta place",
  "englouti par le trou noir du chargeur disparu",
  "coincé dans un GIF qui ne s'arrêtait jamais",
  "renversé par un aspirateur connecté qui avait pris le contrôle",
  "perdu dans une file d'attente virtuelle sans fin",
  "assommé par un clavier mécanique beaucoup trop bruyant",
  "vaincu par la sonnerie d'un téléphone à 1 % de batterie",
  "aspiré dans une imprimante qui refusait toujours d'imprimer",
  "pris au piège dans un tutoriel vidéo de 19 heures",
  "perdu à jamais en cherchant le bouton « accepter les cookies »",
  "renversé par un robot de livraison qui voulait passer en premier",
  "vaincu par un QR code affiché sur ton propre téléphone",
  "coincé dans le cloud en cherchant tes photos de vacances",
  "englouti par un disque dur de 128 Go plein de mises à jour",
  "assommé par une souris sans fil qui avait coupé la connexion",
  "perdu dans les paramètres de confidentialité d'une cafetière",
  "vaincu par un assistant vocal qui avait compris « éteins le monde »",
  "pris au piège dans un écran de chargement à 99 %",
  "emporté par une bulle de savon en faisant la vaisselle",
  "renversé par un caddie qui roulait tout seul",
  "coincé dans une cabine d'essayage de poupée",
  "assommé par un parapluie qui s'ouvrait à l'envers",
  "perdu au milieu d'une pile de reçus de caisse",
  "vaincu par un sac en plastique porté par le vent",
  "englouti par une montagne de tickets de parking",
  "piégé dans une porte automatique qui te prenait pour un fantôme",
  "renversé par un chariot rempli de coussins en promotion",
  "coincé dans une machine à pinces en voulant gagner une peluche",
  "assommé par une boule disco en carton",
  "emporté par un ballon de baudruche mal attaché",
  "perdu dans un magasin de meubles avec trois sorties identiques",
  "vaincu par un escalator qui allait moins vite que toi",
  "coincé dans un photomaton qui imprimait sans s'arrêter",
  "renversé par un mannequin de vitrine qui voulait poser avec toi",
  "assommé par une pluie de prospectus publicitaires",
  "englouti par un bac de chaussettes soldées",
  "pris au piège dans un ascenseur dont tous les boutons disaient « rez-de-chaussée »",
  "perdu en cherchant la sortie d'un parking de supermarché",
  "vaincu par une porte poussée alors qu'il fallait tirer",
  "emporté par un panneau « attention sol glissant »",
  "renversé par une mascotte en forme de paquet de céréales",
  "coincé dans un fauteuil massant qui ne connaissait pas le mode arrêt",
  "assommé par une boule de Noël en polystyrène",
  "perdu dans une file d'attente pour une file d'attente",
  "vaincu par un distributeur de tickets qui n'avait plus de papier",
  "renversé par le vent en faisant semblant d'être un avion",
  "emporté par une piste de luge en tapis de salon",
  "vaincu par le record du monde de saut sur un coussin",
  "coincé dans un trampoline miniature pour enfants",
  "renversé par une balle de ping-pong au ralenti",
  "assommé par un ballon de plage gonflé à moitié",
  "perdu dans une course de sacs alors que tu étais arbitre",
  "pris au piège d'un filet de badminton trop ambitieux",
  "vaincu par un frisbee qui revenait toujours vers toi",
  "emporté par une vague dans une piscine à vagues vide",
  "renversé par un vélo d'appartement qui ne bougeait pas",
  "coincé dans une position de yoga inventée par erreur",
  "assommé par une médaille en chocolat après une course",
  "vaincu par un cerceau au championnat de hula-hoop",
  "perdu en faisant le tour d'une piste d'athlétisme sans fin",
  "emporté par le souffle d'un ventilateur lors d'un sprint",
  "renversé par un tapis de course resté au mode « promenade »",
  "pris au piège dans une tente de camping montée à l'envers",
  "vaincu par un plot de signalisation lors d'un slalom",
  "assommé par une raquette de tennis en mousse",
  "coincé dans un sac de couchage à fermeture éclair rebelle",
  "emporté par un ballon de foot très légèrement dégonflé",
  "perdu dans les vestiaires de ta propre équipe",
  "vaincu par une bouteille d'eau au dernier ravitaillement",
  "renversé par un chronomètre qui avançait plus vite que toi",
  "piégé dans un concours de pompes où personne n'avait dit stop",
  "coincé dans un château gonflable qui refusait de dégonfler",
  "emporté par le lacet d'une chaussure de randonnée",
  "disparu après avoir crié « juste une dernière partie »",
  "aspiré dans un jeu vidéo par l'écran des paramètres",
  "vaincu par le boss du tutoriel en mode très facile",
  "perdu dans un inventaire rempli uniquement de cailloux",
  "pris au piège d'une quête secondaire sur les navets",
  "renversé par une pièce d'échec en mousse",
  "assommé par un dé à vingt faces gonflable",
  "coincé dans une partie de Monopoly qui durait depuis 1998",
  "vaincu par une carte « passe ton tour » devenue réelle",
  "perdu dans un labyrinthe dessiné sur une serviette",
  "emporté par un pion de jeu de l'oie incontrôlable",
  "renversé par une tour de Jenga haute comme un immeuble",
  "pris au piège dans une boîte de jeu sans notice",
  "vaincu par un personnage de jeu qui était niveau un",
  "assommé par une carte Pokémon sortie de sa pochette",
  "coincé dans le menu « appuyer sur une touche »",
  "perdu au niveau zéro d'un jeu qui n'existait pas",
  "vaincu par une manette sans piles au moment crucial",
  "emporté par une animation de victoire trop puissante",
  "renversé par un petit cheval sur un plateau de jeu",
  "pris au piège dans une sauvegarde automatique infinie",
  "assommé par le bouton « rejouer » devenu géant",
  "coincé entre deux pages d'un manga grand format",
  "vaincu au pierre-feuille-ciseaux par un miroir",
  "perdu dans une partie de cache-cache où tu t'étais oublié",
  "emporté par un générique de fin qui ne finissait jamais",
  "renversé par un Rubik's Cube taille XXL",
  "pris au piège dans un karaoké qui affichait les mauvaises paroles",
  "emporté par une valise remplie de chaussettes",
  "coincé dans le compartiment bagages d'un train miniature",
  "perdu dans un aéroport dont tous les panneaux disaient « par là »",
  "renversé par un chariot à bagages qui voulait partir avant toi",
  "assommé par une carte routière dépliée trop vite",
  "vaincu par un GPS qui disait « faites demi-tour » en boucle",
  "englouti par un rond-point qui avait 38 sorties",
  "pris au piège dans un bus touristique sans conducteur",
  "emporté par une trottinette qui ne voulait pas accélérer",
  "coincé dans un pédalo en forme de cygne",
  "renversé par une bouée flamant rose à l'arrêt",
  "perdu sur une plage de sable construite dans un salon",
  "assommé par un panneau « bienvenue » en mousse",
  "vaincu par un billet de train qui refusait de se scanner",
  "coincé dans une cabine de téléphérique au sol",
  "emporté par un tapis roulant d'aéroport en sens inverse",
  "renversé par un avion en papier lancé à trois mètres",
  "pris au piège dans une carte postale trop réaliste",
  "perdu dans un hôtel dont toutes les chambres portaient ton nom",
  "vaincu par une serviette de plage qui s'envolait toujours",
  "assommé par un coquillage géant en plastique",
  "coincé dans un gilet de sauvetage pour peluche",
  "emporté par une vague de confettis au bord d'une piscine",
  "perdu dans un camping où toutes les tentes étaient identiques",
  "renversé par une voiturette de golf décorative",
  "vaincu par un panneau « vous êtes ici » qui bougeait",
  "pris au piège dans une chambre d'hôtel à 48 oreillers",
  "assommé par un passeport tombé de ton sac",
  "emporté par des applaudissements trop enthousiastes",
  "coincé dans une poignée de main qui ne finissait pas",
  "vaincu par une blague de papa au pire moment",
  "englouti par une montagne de cadeaux emballés",
  "renversé par un gâteau factice à un mariage",
  "assommé par un bouquet de fleurs en plastique",
  "pris au piège dans un photobooth aux rideaux infinis",
  "perdu dans une soirée où tout le monde portait le même costume",
  "emporté par une chenille humaine à une fête d'anniversaire",
  "vaincu par un discours de remerciement de neuf heures",
  "coincé dans une danse du limbo à hauteur de plafond",
  "renversé par une pluie de pétales de rose",
  "assommé par une couronne en carton lors d'une fête",
  "perdu dans les coulisses d'un spectacle de marionnettes",
  "pris au piège dans un câlin collectif trop organisé",
  "emporté par un lancer de confettis raté",
  "vaincu par un mime qui refusait d'ouvrir sa boîte imaginaire",
  "coincé dans une photo de groupe dont personne ne partait",
  "assommé par une boule à facettes en papier",
  "renversé par une vague de chapeaux lancés en l'air",
  "perdu dans une soirée surprise organisée pour quelqu'un d'autre",
  "vaincu par un magicien qui avait oublié son tour",
  "pris au piège dans un ballon d'anniversaire en forme de toi",
  "emporté par une foule de fans de la même chanson",
  "coincé dans une séance d'autographes où tu étais le stylo",
  "assommé par un trophée en mousse au concours de danse",
  "perdu dans un concours de déguisements où tu étais juge",
  "pris au piège dans un photomontage devenu réel",
  "emporté par un nuage qui voulait te servir de taxi",
  "coincé dans une dimension faite uniquement de couvertures",
  "vaincu par une licorne qui avait le hoquet",
  "perdu dans une réunion de pingouins en costume",
  "renversé par un dinosaure gonflable en retard au travail",
  "assommé par une étoile filante tombée au ralenti",
  "pris au piège dans un ascenseur qui montait vers la Lune",
  "emporté par une tornade de plumes de canard",
  "vaincu par une statue qui voulait changer de place",
  "coincé dans une bataille de bulles de savon intergalactique",
  "perdu au bout d'un arc-en-ciel mal indiqué",
  "renversé par un fantôme qui avait oublié qu'il traversait les murs",
  "assommé par une météorite en guimauve",
  "pris au piège d'une baguette magique en panne",
  "emporté par une cape de super-héros trop longue",
  "vaincu par un dragon miniature qui éternuait des confettis",
  "coincé dans une machine à voyager uniquement les mardis",
  "perdu dans un labyrinthe de miroirs sans entrée",
  "renversé par une planète gonflable à taille réelle",
  "assommé par une couronne de roi en chocolat",
  "pris au piège dans un château de sable construit sur un nuage",
  "emporté par un vortex ouvert derrière le frigo",
  "vaincu par un chevalier armé d'une cuillère en plastique",
  "coincé dans une prophétie écrite en tout petits caractères",
  "perdu dans un rêve où ton réveil était le boss final",
  "renversé par ton double venu d'un univers plus maladroit",
  "assommé par une comète fabriquée en papier mâché",
  "pris au piège dans une machine à remonter le temps qui reculait d'une seconde"
];

const REALISTIC_DEATHS = [
  "de vieillesse, paisiblement chez toi",
  "de vieillesse, entouré de ta famille",
  "de vieillesse dans ton sommeil",
  "de vieillesse après une longue retraite",
  "de vieillesse après avoir rencontré tes arrière-petits-enfants",
  "de vieillesse à l'hôpital",
  "de vieillesse dans une maison de retraite",
  "à la suite d'un accident de voiture sur l'autoroute",
  "à la suite d'un accident de voiture sur une route de campagne",
  "à la suite d'un accident de voiture en rentrant du travail",
  "à la suite d'un accident de voiture pendant les vacances",
  "à la suite d'un accident de voiture de nuit",
  "à la suite d'un accident de voiture sous une forte pluie",
  "à la suite d'un accident de voiture sur une route verglacée",
  "à la suite d'un accident vasculaire cérébral",
  "à la suite d'un infarctus",
  "à la suite d'un arrêt cardiaque pendant ton sommeil",
  "à la suite d'un arrêt cardiaque lors d'une promenade",
  "à la suite d'une maladie cardiaque",
  "à la suite d'une insuffisance respiratoire",
  "à la suite d'une infection pulmonaire",
  "dans un incendie domestique",
  "dans un incendie d'immeuble",
  "dans un incendie à l'hôtel",
  "dans un incendie de forêt près de chez toi",
  "dans un incendie sur ton lieu de travail",
  "à la suite d'une fuite de gaz chez toi",
  "à la suite d'une intoxication au monoxyde de carbone",
  "dans une avalanche en montagne",
  "dans une avalanche pendant une sortie à ski",
  "dans une avalanche lors d'une randonnée hivernale",
  "à la suite d'une chute en randonnée",
  "à la suite d'une chute en escalade",
  "à la suite d'une chute sur un sentier de montagne",
  "après t'être perdu en montagne par mauvais temps",
  "à la suite d'un accident de ski",
  "à la suite d'un accident de snowboard",
  "à la suite d'un accident de parapente",
  "à la suite d'un accident de parachutisme",
  "à la suite d'un accident d'équitation",
  "à la suite d'un accident de karting",
  "à la suite d'un accident sur circuit automobile",
  "à la suite d'un accident sur un chantier",
  "à la suite d'une chute sur ton lieu de travail",
  "à la suite d'un accident dans une usine",
  "à la suite d'un accident dans un entrepôt",
  "à la suite d'un accident lors d'une livraison",
  "à la suite d'un accident pendant un déplacement professionnel",
  "à la suite d'un accident avec une machine industrielle",
  "dans un accident d'avion",
  "dans un accident d'hélicoptère",
  "dans un accident de petit avion de tourisme",
  "dans un accident de train",
  "dans un accident de métro",
  "dans un accident de tramway",
  "dans un accident de ferry",
  "à la suite d'un malaise dans les transports",
  "à la suite d'un malaise au travail",
  "à la suite d'un malaise pendant un voyage",
  "à la suite d'un malaise à domicile",
  "à la suite d'un malaise dans la rue",
  "à la suite d'un arrêt cardiaque au travail",
  "à la suite d'un arrêt cardiaque dans un train",
  "à la suite d'une chute sur un quai de gare",
  "à la suite d'un accident sur un passage à niveau",
  "à la suite d'un accident sur un chantier routier",
  "à la suite d'une collision entre un vélo et une voiture",
  "à la suite d'une collision entre une moto et un camion",
  "à la suite d'une collision entre deux bus",
  "à la suite d'une collision entre un train et un véhicule",
  "à la suite d'un incendie dans un camping",
  "à la suite d'un incendie dans une résidence",
  "à la suite d'un incendie dans un restaurant",
  "à la suite d'un incendie dans un garage",
  "à la suite d'une explosion accidentelle dans un immeuble",
  "à la suite d'une explosion accidentelle sur un chantier",
  "à la suite d'une fuite de gaz dans un immeuble",
  "à la suite d'une inondation pendant une tempête",
  "à la suite d'une crue en traversant une route",
  "à la suite d'une crue pendant une randonnée",
  "à la suite d'une tempête sur un voilier",
  "à la suite d'une tempête en montagne",
  "à la suite d'une tempête tropicale pendant un voyage",
  "à la suite d'une vague de chaleur en ville",
  "après une longue vie et une dernière promenade",
  "après une longue vie passée à enseigner",
  "après une longue vie passée à soigner les autres",
  "après une longue vie consacrée à ta famille",
  "après une longue vie passée à voyager",
  "après une longue vie dans le même village",
  "après une longue vie au bord de la mer"
];

const DEATHS = Object.freeze([...RIDICULOUS_DEATHS, ...REALISTIC_DEATHS]);
