"use strict";

// 150 fins d’humour noir + 150 fins réalistes. Toutes sont fictives.
const DARK_DEATHS = [
  "noyé en buvant une canette de Coca pendant un concours de descente",
  "étouffé par un glaçon en voulant prouver que tu avalais tout rond",
  "mort après avoir avalé de travers une frite, juste devant un secouriste",
  "étouffé par la fève de la galette après avoir crié « j'ai gagné ! »",
  "mort asphyxié par une cacahuète au buffet d'une formation aux premiers secours",
  "mort d'une allergie en goûtant le gâteau « garanti sans allergènes »",
  "étouffé par une bouchée de steak pendant un concours de mastication",
  "noyé dans une cuve de soda après y avoir fait tomber ton téléphone",
  "mort brûlé en voulant goûter le caramel directement dans la casserole",
  "mort écrasé par une armoire frigorifique en cherchant une bouteille d'eau",
  "mort écrasé par un distributeur de boissons secoué pour récupérer 2 euros",
  "mort électrocuté en essayant de récupérer une tartine dans le grille-pain",
  "mort étouffé par la fumée en faisant griller une unique marshmallow",
  "mort brûlé après avoir flambé un dessert pour impressionner tes invités",
  "mort empoisonné par les champignons cueillis grâce à une application qui se trompait",
  "mort étouffé par une bouchée de gâteau pendant qu'on chantait ton anniversaire",
  "mort après avoir confondu le produit pour lave-vaisselle et le sirop de menthe",
  "mort brûlé en tentant d'éteindre de l'huile en feu avec un verre d'eau",
  "mort écrasé par une palette de bouteilles pendant une promotion sur l'eau",
  "mort étouffé par un bonbon que tu avais avalé pour cacher une gourmandise",
  "mort foudroyé en posant pour une photo sous le seul arbre d'une prairie",
  "mort noyé en voulant sauver un téléphone tombé dans un pédalo",
  "mort écrasé par le panneau « attention chute d'objets » qu'on installait",
  "mort après avoir chuté du toit en fixant une affiche « sécurité d'abord »",
  "mort électrocuté en touchant une clôture pour vérifier si elle marchait",
  "mort asphyxié par le monoxyde de carbone après avoir bouché le détecteur qui bipait",
  "mort en tombant d'une échelle sur le point de ranger cette même échelle",
  "mort renversé en traversant pour lire un panneau « passage interdit »",
  "mort écrasé par une porte coupe-feu pendant un exercice d'évacuation",
  "mort noyé dans une piscine en testant si tes brassards d'enfant tenaient encore",
  "mort électrocuté par le micro pendant ton discours sur la prévention des risques",
  "mort après avoir glissé sur la flaque que tu venais de signaler avec un panneau",
  "mort asphyxié en entrant dans une pièce pour réparer l'alarme incendie",
  "mort en chutant pendant que tu photographiais le panneau « danger falaise »",
  "mort coincé sous le véhicule après avoir retiré le cric « juste une seconde »",
  "mort écrasé par ta voiture en voulant lui montrer qu'elle roulait au point mort",
  "mort renversé par le bus en courant pour ne pas le rater",
  "mort dans un carambolage après avoir voulu ramasser ton chewing-gum sous le siège",
  "mort percuté par ta propre voiture après avoir oublié le frein à main",
  "mort électrocuté en rechargeant ton téléphone dans une baignoire",
  "mort noyé dans un fossé en voulant récupérer tes clés tombées de la voiture",
  "mort dans un accident en suivant le GPS qui disait de faire demi-tour sur l'autoroute",
  "mort renversé par un camion pendant que tu lui faisais signe de reculer",
  "mort écrasé par une camionnette de déménagement remplie de coussins",
  "mort en passant par le toit ouvrant pour attraper un ticket de péage envolé",
  "mort dans une collision provoquée par une vidéo sur la sécurité routière que tu regardais",
  "mort percuté par un vélo après avoir sauté sur la piste cyclable pour éviter une trottinette",
  "mort écrasé par ton propre vélo cargo chargé de bouteilles d'eau",
  "mort percuté par le taxi que tu avais appelé parce que tu ne voulais pas marcher",
  "mort sur le chantier écrasé par le panneau « chantier terminé » qu'on décrochait",
  "mort écrasé par la pile de casques de protection que tu livrais",
  "mort enseveli sous les cartons de papier bulle que tu avais empilés trop haut",
  "mort électrocuté en réparant la machine à café du service informatique",
  "mort asphyxié dans une chambre froide en cherchant une seule glace",
  "mort écrasé par une machine à fabriquer des panneaux « danger machine »",
  "mort en chutant d'un échafaudage en allant récupérer un harnais oublié",
  "mort écrasé par une palette de matelas pendant une démonstration de confort",
  "mort brûlé en voulant souffler sur une bougie près d'un bidon de solvant",
  "mort coincé dans un compacteur après avoir voulu récupérer ton badge",
  "mort frappé à la tête par l'horloge géante que tu venais de réparer",
  "mort électrocuté en installant l'enseigne lumineuse d'un magasin de bougies",
  "mort écrasé par un stock de bouées de piscine tombé d'une étagère",
  "mort en tombant dans l'escalier en portant le nouveau panneau « attention escalier »",
  "mort asphyxié par les fumées d'un photocopieur dont tu voulais absolument tirer une dernière copie",
  "mort noyé en essayant de retrouver une pièce de monnaie au fond d'une fontaine",
  "mort électrocuté en cherchant pourquoi le sèche-cheveux ne s'allumait plus sous la douche",
  "mort après avoir glissé sur le savon que tu venais de ranger",
  "mort écrasé par la bibliothèque que tu fixais justement au mur",
  "mort étouffé par la fumée d'une bougie laissée sur le carton des bougies",
  "mort après être tombé du balcon en secouant le tapis d'entrée",
  "mort assommé par un cadre « home sweet home » mal accroché",
  "mort brûlé en testant une couverture « ignifugée » achetée sur Internet",
  "mort noyé dans une piscine gonflable en voulant y faire une vidéo dramatique",
  "mort en chutant dans la cave pour vérifier si la lumière fonctionnait",
  "mort intoxiqué après avoir mélangé deux produits ménagers pour gagner du temps",
  "mort écrasé par la télévision en voulant empêcher une télécommande de tomber",
  "mort étouffé par la fumée en grillant du pain pour la troisième fois",
  "mort électrocuté par la guirlande que tu voulais installer avant Noël",
  "mort en tombant du grenier en cherchant une boîte marquée « ne pas perdre »",
  "mort électrocuté en débranchant la multiprise avec une fourchette",
  "mort asphyxié par la fumée en imprimant un message « tout va bien »",
  "mort écrasé par une borne automatique que tu secouais parce qu'elle affichait « erreur »",
  "mort en chutant d'un balcon pour récupérer le drone qui filmait la chute",
  "mort renversé en traversant sans regarder parce que tu suivais un itinéraire sur ton téléphone",
  "mort électrocuté en branchant une rallonge pour recharger une batterie externe dans l'eau",
  "mort écrasé par un écran géant pendant une démonstration de réalité virtuelle",
  "mort étouffé par la fumée d'un chargeur brûlant que tu refusais de débrancher",
  "mort dans un accident de voiture en voulant fermer une publicité sur ton GPS",
  "mort écrasé par un robot de livraison en essayant de le remettre debout sur une pente",
  "mort frappé par une antenne en montant sur le toit pour capter une barre de réseau",
  "mort brûlé après avoir suivi un tutoriel bricolage qui sautait une étape",
  "mort électrocuté en testant un détecteur de tension avec la mauvaise main",
  "mort en chutant de vélo pendant que tu choisissais le filtre de ta vidéo",
  "mort asphyxié en réparant le ventilateur qui évacuait les fumées",
  "mort écrasé par une imprimante 3D de taille industrielle fabriquant un buste de toi",
  "mort en tombant d'une échelle en essayant de retrouver le Wi-Fi dans le grenier",
  "mort noyé après avoir voulu filmer sous l'eau avec un téléphone non étanche",
  "mort écrasé par un panier de basket en voulant dunker sans ballon",
  "mort étouffé par la barre de musculation après avoir annoncé « je gère »",
  "mort d'un arrêt cardiaque en sprinter pour attraper un bus qui était à l'arrêt",
  "mort écrasé par des poids en voulant filmer un record que tu n'avais jamais tenté",
  "mort noyé dans un bassin pour récupérer la médaille tombée après ta course",
  "mort en chutant d'un tapis de course que tu avais réglé sur « vitesse de marche »",
  "mort percuté par un javelot en donnant des conseils au lanceur",
  "mort en tombant à ski après t'être arrêté pour montrer comment freiner",
  "mort étouffé par un protège-dents lors d'une démonstration de sécurité",
  "mort en chutant d'un mur d'escalade en voulant vérifier si le tapis était assez épais",
  "mort frappé par un disque en voulant faire une photo au milieu du terrain",
  "mort écrasé sous un vélo d'appartement industriel pendant son montage",
  "mort noyé après avoir juré que la bouée n'était « que pour les débutants »",
  "mort après avoir reçu un coup de boule en arbitrant un concours de danse",
  "mort foudroyé en brandissant ton trophée métallique sous l'orage",
  "mort en tombant du podium en voulant prendre un selfie de ta victoire",
  "mort dans une avalanche en revenant chercher tes lunettes de soleil",
  "mort noyé en allant récupérer un ballon flottant après la fermeture de la plage",
  "mort foudroyé en plantant un parasol métallique sous l'orage",
  "mort de froid en revenant chercher ton téléphone dans un igloo touristique",
  "mort en chutant d'une falaise pour cadrer la mer sans touristes",
  "mort emporté par une vague après avoir dit « elle est toute petite »",
  "mort intoxiqué par le barbecue allumé dans une tente pour éviter la pluie",
  "mort noyé en voulant rejoindre une bouée plus belle que celle que tu avais",
  "mort écrasé par un rocher en te cachant dessous pour éviter quelques gouttes de pluie",
  "mort électrocuté en branchant ton enceinte juste à côté d'une piscine",
  "mort en tombant d'une cascade pour récupérer une sandale à dix euros",
  "mort mordu par un serpent pendant que tu montrais qu'il était inoffensif",
  "mort après une allergie à la crème solaire vendue « spéciale peaux sensibles »",
  "mort dans un accident de pédalo en essayant de dépasser un vrai bateau",
  "mort en chutant du quai pour sauver ton chapeau emporté par le vent",
  "mort foudroyé pendant que tu annonçais que l'orage passait au loin",
  "mort emporté par une crue en filmant « le petit ruisseau »",
  "mort étouffé par une cacahuète en racontant ta pire anecdote d'étouffement",
  "mort en tombant de la scène avant d'avoir prononcé « faites attention à la marche »",
  "mort écrasé par l'arche de bienvenue de ton propre mariage",
  "mort asphyxié par la fumée des bougies que tout le monde voulait allumer en même temps",
  "mort après avoir avalé de travers au milieu d'un concours de blagues",
  "mort écrasé par la tour de cadeaux en voulant sauver le plus petit",
  "mort en chutant de la scène pendant ton discours sur les accidents domestiques",
  "mort électrocuté par le micro au moment de dire « je suis immortel »",
  "mort noyé dans la fontaine où tu avais voulu lancer une pièce pour porter chance",
  "mort en chutant du balcon pour rattraper le bouquet de la mariée",
  "mort écrasé par la banderole « longue vie à toi » qui s'est décrochée",
  "mort d'une allergie au gâteau surprise dont tu avais demandé la composition",
  "mort en glissant sur les confettis du panneau « félicitations »",
  "mort écrasé par une statue qu'on inaugurait à ton nom",
  "mort asphyxié par une machine à fumée pendant un spectacle sur la qualité de l'air",
  "mort le crâne fracassé par le trophée de « personne la plus prudente »",
  "mort brûlé vif en soufflant sur un feu que tu croyais éteint",
  "mort étouffé, les poumons pleins de soda, après avoir voulu boire tête en bas",
  "mort écrasé par le cercueil vide utilisé pour une blague qui tournait mal",
  "mort après t'être empalé sur le portique « attention à votre sécurité »"
];

const REALISTIC_DEATHS = [
  "de vieillesse, paisiblement chez toi",
  "de vieillesse, entouré de ta famille",
  "de vieillesse dans ton sommeil",
  "de vieillesse après une longue retraite",
  "de vieillesse après avoir rencontré tes arrière-petits-enfants",
  "de vieillesse à l'hôpital",
  "de vieillesse dans une maison de retraite",
  "à la suite d'un accident de voiture sur l'autoroute",
  "à la suite d'un accident de voiture sur une route de campagne",
  "à la suite d'un accident de voiture en rentrant du travail",
  "à la suite d'un accident de voiture pendant les vacances",
  "à la suite d'un accident de voiture de nuit",
  "à la suite d'un accident de voiture sous une forte pluie",
  "à la suite d'un accident de voiture sur une route verglacée",
  "à la suite d'un accident vasculaire cérébral",
  "à la suite d'un infarctus",
  "à la suite d'un arrêt cardiaque pendant ton sommeil",
  "à la suite d'un arrêt cardiaque lors d'une promenade",
  "à la suite d'une maladie cardiaque",
  "à la suite d'une insuffisance respiratoire",
  "à la suite d'une infection pulmonaire",
  "dans un incendie domestique",
  "dans un incendie d'immeuble",
  "dans un incendie à l'hôtel",
  "dans un incendie de forêt près de chez toi",
  "dans un incendie sur ton lieu de travail",
  "à la suite d'une fuite de gaz chez toi",
  "à la suite d'une intoxication au monoxyde de carbone",
  "dans une avalanche en montagne",
  "dans une avalanche pendant une sortie à ski",
  "dans une avalanche lors d'une randonnée hivernale",
  "à la suite d'une chute en randonnée",
  "à la suite d'une chute en escalade",
  "à la suite d'une chute sur un sentier de montagne",
  "après t'être perdu en montagne par mauvais temps",
  "à la suite d'un accident de ski",
  "à la suite d'un accident de snowboard",
  "à la suite d'un accident de parapente",
  "à la suite d'un accident de parachutisme",
  "à la suite d'un accident d'équitation",
  "à la suite d'un accident de karting",
  "à la suite d'un accident sur circuit automobile",
  "à la suite d'un accident sur un chantier",
  "à la suite d'une chute sur ton lieu de travail",
  "à la suite d'un accident dans une usine",
  "à la suite d'un accident dans un entrepôt",
  "à la suite d'un accident lors d'une livraison",
  "à la suite d'un accident pendant un déplacement professionnel",
  "à la suite d'un accident avec une machine industrielle",
  "dans un accident d'avion",
  "dans un accident d'hélicoptère",
  "dans un accident de petit avion de tourisme",
  "dans un accident de train",
  "dans un accident de métro",
  "dans un accident de tramway",
  "dans un accident de ferry",
  "à la suite d'un malaise dans les transports",
  "à la suite d'un malaise au travail",
  "à la suite d'un malaise pendant un voyage",
  "à la suite d'un malaise à domicile",
  "à la suite d'un malaise dans la rue",
  "à la suite d'un arrêt cardiaque au travail",
  "à la suite d'un arrêt cardiaque dans un train",
  "à la suite d'une chute sur un quai de gare",
  "à la suite d'un accident sur un passage à niveau",
  "à la suite d'un accident sur un chantier routier",
  "à la suite d'une collision entre un vélo et une voiture",
  "à la suite d'une collision entre une moto et un camion",
  "à la suite d'une collision entre deux bus",
  "à la suite d'une collision entre un train et un véhicule",
  "à la suite d'un incendie dans un camping",
  "à la suite d'un incendie dans une résidence",
  "à la suite d'un incendie dans un restaurant",
  "à la suite d'un incendie dans un garage",
  "à la suite d'une explosion accidentelle dans un immeuble",
  "à la suite d'une explosion accidentelle sur un chantier",
  "à la suite d'une fuite de gaz dans un immeuble",
  "à la suite d'une inondation pendant une tempête",
  "à la suite d'une crue en traversant une route",
  "à la suite d'une crue pendant une randonnée",
  "à la suite d'une tempête sur un voilier",
  "à la suite d'une tempête en montagne",
  "à la suite d'une tempête tropicale pendant un voyage",
  "à la suite d'une vague de chaleur en ville",
  "après une longue vie et une dernière promenade",
  "après une longue vie passée à enseigner",
  "après une longue vie passée à soigner les autres",
  "après une longue vie consacrée à ta famille",
  "après une longue vie passée à voyager",
  "après une longue vie dans le même village",
  "après une longue vie au bord de la mer",
  "à la suite d'une crise cardiaque pendant une promenade",
  "à la suite d'un accident vasculaire cérébral durant la nuit",
  "à la suite d'une complication liée à une infection respiratoire",
  "à la suite d'une embolie pulmonaire",
  "à la suite d'une rupture d'anévrisme",
  "à la suite d'une insuffisance rénale chronique",
  "à la suite d'une complication d'une maladie auto-immune",
  "à la suite d'une réaction allergique sévère à un médicament",
  "à la suite d'une défaillance cardiaque à domicile",
  "à la suite d'une complication après une opération",
  "à la suite d'un accident de voiture dans un tunnel",
  "à la suite d'un accident de moto sur une route de montagne",
  "à la suite d'une collision avec un poids lourd",
  "à la suite d'un accident de bus scolaire alors que tu étais passager",
  "à la suite d'un accident de la route pendant un déplacement professionnel",
  "à la suite d'un accident de vélo sur le trajet du travail",
  "à la suite d'un accident de train lors d'un voyage",
  "à la suite d'un accident sur un passage à niveau rural",
  "à la suite d'un accident de scooter dans une intersection",
  "à la suite d'un accident de taxi pendant un trajet de nuit",
  "à la suite d'une avalanche pendant une randonnée hivernale",
  "à la suite d'un glissement de terrain après de fortes pluies",
  "à la suite d'une noyade au cours d'une baignade",
  "à la suite d'une noyade après un accident de bateau",
  "à la suite d'une chute de pierres en montagne",
  "à la suite d'une hypothermie en mer",
  "à la suite d'un incendie de forêt pendant une randonnée",
  "à la suite d'une crue soudaine dans une vallée",
  "à la suite d'un orage violent en mer",
  "à la suite d'une vague de chaleur prolongée",
  "à la suite d'une chute d'échafaudage sur un chantier",
  "à la suite d'un accident avec une presse industrielle",
  "à la suite d'une électrocution lors de travaux",
  "à la suite d'un incendie dans un atelier",
  "à la suite d'une explosion accidentelle dans une usine",
  "à la suite d'un accident agricole",
  "à la suite d'un accident de grue sur un chantier",
  "à la suite d'un accident dans une mine",
  "à la suite d'une intoxication sur un site industriel",
  "à la suite d'un accident lors d'une intervention de secours",
  "à la suite d'un incendie d'appartement",
  "à la suite d'une intoxication au monoxyde de carbone pendant la nuit",
  "à la suite d'une chute dans un escalier",
  "à la suite d'une chute depuis un balcon",
  "à la suite d'un accident de bricolage à domicile",
  "à la suite d'une fuite de gaz dans une maison individuelle",
  "à la suite d'un accident dans une piscine privée",
  "à la suite de l'effondrement d'une toiture",
  "à la suite d'une chute d'une échelle",
  "à la suite d'une infection après une blessure",
  "à la suite d'un accident de parapente au-dessus d'une vallée",
  "à la suite d'un accident d'escalade",
  "à la suite d'un accident de plongée",
  "à la suite d'un accident d'équitation pendant une randonnée",
  "à la suite d'un malaise pendant un marathon",
  "à la suite d'un accident de ski de fond en montagne",
  "à la suite d'un accident de rafting",
  "à la suite d'un accident pendant une sortie en voile",
  "à la suite d'un accident de vélo lors d'une course"
];

const DEATHS = Object.freeze([...DARK_DEATHS, ...REALISTIC_DEATHS]);
